### ISSUE TITLE
remove branch refactor-ast_remove-cardinality-from-triple-constraint?

### ISSUE THREAD

**Issue by ericprud** [fhircat/jena#6]
I think we're done with [`refactor-ast_remove-cardinality-from-triple-constraint`](https://github.com/fhircat/jena/tree/refactor-ast_remove-cardinality-from-triple-constraint).

[`refactor-ast...refactor-ast_remove-cardinality-from-triple-constraint`](https://github.com/fhircat/jena/compare/refactor-ast...refactor-ast_remove-cardinality-from-triple-constraint) shows no pending diffs.

Delete it or tell me to if you agree.

**Comment by iovka** [comment]
agree
