### ISSUE TITLE
test schema added only one format

### ISSUE THREAD

**Issue by iovka** [fhircat/jena#7]
### Change

In refactor-ast branch: added test schema 
`/files/shexTest/schemas/ExtendsHierarchy.shex`
needed to test schema structural validity, but not used in tests

1. If this is the right place for such schema, the corresponding .json and .ttl versions are to be added
2. If this is not the right place, then it should be moved 

### Are you interested in contributing a pull request for this task?

None

**Comment by ericprud** [comment]
done -- https://github.com/fhircat/jena/commit/fc0bded19ed3260092e6f79f454f8619661324bd
